-- plugins
require('hexatom.options')
require('hexatom.lazy')
require('hexatom.treesitter')
require('hexatom.colorscheme')
require('hexatom.whichkey')
require('hexatom.completions')
require('hexatom.lsp')
require('hexatom.telescope')
require('hexatom.comment')
require('hexatom.gitsigns')
require('hexatom.nvimtree')
require('hexatom.bufferline')
require('hexatom.toggleterm')
require('hexatom.rainbow-delimiters')
require('hexatom.undotree')
require('hexatom.lualine')
require('hexatom.spectre')
require('hexatom.ufo')
require('hexatom.wilder')
-- custom
require("hexatom.vertical_help")
