#!/usr/bin/env zsh

## Loading Section
autoload compinit colors zcalc

if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
    compinit;
else
    compinit -C;
fi;

## Environment Section
export EDITOR='nvim'
export BROWSER='/usr/bin/firefox'
export SSH_KEY_PATH='~/.ssh/rsa_id'
export LESSHISTFILE='-'
export MANPAGER="/usr/bin/less -s -M +Gg"
export KUBECONFIG="$HOME/.config/kube/config"
export TERM='tmux-256color'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --no-ignore --follow'
export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'
export EXA_COLORS="uu=36:gu=37:sn=32:sb=32:da=34:ur=34:uw=35:ux=36:ue=36:gr=34:gw=35:gx=36:tr=34:tw=35:tx=36:"
export LESS_TERMCAP_mb=$'\e[1;31m'      # begin bold
export LESS_TERMCAP_md=$'\e[1;34m'      # begin blink
export LESS_TERMCAP_so=$'\e[01;45;37m'  # begin reverse video
export LESS_TERMCAP_us=$'\e[01;36m'     # begin underline
export LESS_TERMCAP_me=$'\e[0m'         # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'         # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'         # reset underline
export GROFF_NO_SGR=1                   # for konsole

## Alias Section
# General
alias df='df -h'
alias sdn='shutdown now'
alias sdrn='shutdown -r now'
alias sc='i3-scrot -sc --line mode=edge'

# Replacement Section
alias ls='eza'
alias la='eza -lah --git'
alias find='fd'
alias e='nvim'

# Git
alias gs='git status'
alias gf='git fetch -p --tags'
alias ga='git add -p'
alias gc='git commit -s'
alias gp='git push'
alias gl='git pull'
alias gitu='git add . && git commit && git push'
alias gcob='git checkout -b'
alias gco='git checkout'

# Docker
alias dkrps='docker ps'
alias dkrpsa='docker ps -a'

# Kubectl
alias k='kubectl'
alias kcu='kubectl config use-context'

# Programs
alias tmux='tmux -f ~/.config/tmux/tmux.conf'
alias less='less -XRF'
alias spotify='spotify --force-device-scale-factor=2'
alias fzf='fzf --preview "bat --color=always --style=numbers --line-range=:500 {}"'
alias bat='bat --color=always'

# dir movement
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

## Options Section
setopt appendhistory
setopt extendedglob
setopt histignorealldups
setopt histignorespace
setopt interactivecomments
setopt nocaseglob
setopt numericglobsort
setopt promptsubst
setopt rcexpandparam
setopt checkjobs

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' rehash true
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.config/zsh/cache
HISTFILE=~/.config/zsh/zsh_history
HISTSIZE=1000
SAVEHIST=500
WORDCHARS=${WORDCHARS//\/[&.;]}

## Keybinding Section
bindkey -v

# Home Key
bindkey '^[[7~' beginning-of-line
bindkey '^[[H' beginning-of-line

# End Key
bindkey '^[[8~' end-of-line
bindkey '^[[F' end-of-line

# Search
bindkey '^[[5~' history-beginning-search-backward # Page up key
bindkey '^[[6~' history-beginning-search-forward  # Page down key
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

## Theme Section
colors
source ~/data/dracula-theme/zsh-syntax-highlighting/zsh-syntax-highlighting.sh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=7'

## Plugin Section
source $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/plugins/zsh-git-prompt/zshrc.sh
source $ZDOTDIR/plugins/zsh-kubectl-prompt/kubectl.zsh
source <(kubectl completion zsh)
source <(minikube completion zsh)
source <(k9s completion zsh)
source <(kube-linter completion zsh)
source <(terraform-docs completion zsh)

## git prompt config
ZSH_THEME_GIT_PROMPT_PREFIX="["
ZSH_THEME_GIT_PROMPT_SUFFIX="]"
ZSH_THEME_GIT_PROMPT_HASH_PREFIX=":"
ZSH_THEME_GIT_PROMPT_SEPARATOR="|"
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[magenta]%}"
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[red]%}%{●%G%}"
ZSH_THEME_GIT_PROMPT_CONFLICTS="%{$fg[red]%}%{󱐋%G%}"
ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[blue]%}%{%G%}"
ZSH_THEME_GIT_PROMPT_BEHIND="%{↓%1G%}"
ZSH_THEME_GIT_PROMPT_BEHIND_AHEAD_SEPARATOR=""
ZSH_THEME_GIT_PROMPT_BEHIND_AHEAD_SECTION_SEPARATOR=" "
ZSH_THEME_GIT_PROMPT_AHEAD="%{↑%1G%}"
ZSH_THEME_GIT_PROMPT_STASHED="%{$fg_bold[blue]%}%{%G%}"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[cyan]%}%{󰈉%G%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}%{✔%G%}"
ZSH_THEME_GIT_PROMPT_LOCAL=" L"
# The remote branch will be shown between these two
ZSH_THEME_GIT_PROMPT_UPSTREAM_FRONT=" {%{$fg[blue]%}"
ZSH_THEME_GIT_PROMPT_UPSTREAM_END="%{${reset_color}%}}"
ZSH_THEME_GIT_PROMPT_MERGING="%{$fg_bold[magenta]%}|MERGING%{${reset_color}%}"
ZSH_THEME_GIT_PROMPT_REBASE="%{$fg_bold[magenta]%}|REBASE%{${reset_color}%} "
ZSH_THEME_GIT_PROMPT_BISECT="%{$fg_bold[magenta]%}|BISECT%{${reset_color}%} "

# Settings defaults
ZSH_GIT_PROMPT_SHOW_UPSTREAM=0
ZSH_GIT_PROMPT_SHOW_BEHIND=1
ZSH_GIT_PROMPT_SHOW_AHEAD=1
ZSH_GIT_PROMPT_SHOW_REBASE=1
ZSH_GIT_PROMPT_SHOW_MERGING=1
ZSH_GIT_PROMPT_SHOW_BISECT=1
ZSH_GIT_PROMPT_SHOW_STAGED=1
ZSH_GIT_PROMPT_SHOW_CONFLICTS=1
ZSH_GIT_PROMPT_SHOW_CHANGED=1
ZSH_GIT_PROMPT_SHOW_UNTRACKED=1
ZSH_GIT_PROMPT_SHOW_STASHED=1

## Primary prompt
PS1='\
%F{reset_color}[ \
%B%F{14}%D%b \
%B%F{14}%T%b\
%F{reset_color} ] \
%B%F{11}%n%b\
%F{reset_color%}@\
%B%F{10}%m%b\
%B%F{12}%~%b \
%F{13}<$ZSH_KUBECTL_CONTEXT> \
%F{reset_color}$(git_super_status)
 %F{12}»\
%F{reset_color} \
'

## Local source
source ~/.config/zsh/.zshrc.local

## Tmux Section
if [[ -z "$TMUX" ]] ;then
    ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )"
    if [[ -z "$ID" ]] ;then
        tmux new-session
    else
        tmux attach-session -t "$ID"
    fi
fi

