#!/usr/bin/env zsh

## Loading Section
autoload compinit colors zcalc

if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
    compinit;
else
    compinit -C;
fi;

## Environment Section
export EDITOR='nvim'
export BROWSER='/usr/bin/firefox'
export SSH_KEY_PATH='~/.ssh/rsa_id'
export LESSHISTFILE='-'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export KUBECONFIG="$HOME/.kube/config:$HOME/.kube/kubeconfigs/funkedigital/fd-cloud.yaml"
export PATH="$PATH:$HOME/data/scripts:$HOME/.krew/bin:$HOME/go/bin"
export TERM='tmux-256color'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --no-ignore --follow'

## Alias Section
# General
alias df='df -h'
alias sdn='shutdown now'
alias sdrn='shutdown -r now'
alias updateSystem='sudo pacman -Syyu'
alias trexa='exa -Ta'
alias trexad='exa -TaD'
alias sc='i3-scrot -sc --line mode=edge'

# Replacement Section
alias ls='exa'
alias la='exa -lah --git'
alias find='fd'
alias e='nvim'

# Git
alias gs='git status'
alias gf='git fetch -p --tags'
alias ga='git add -p'
alias gc='git commit -s'
alias gp='git push'
alias gpt='git push --tags'
alias gl='git pull'
alias gitu='git add . && git commit && git push'
alias gcob='git checkout -b'
alias gco='git checkout'

# Docker
alias dkrps='docker ps'
alias dkrpsa='docker ps -a'

# Kubectl
alias k='kubectl'
alias kcu='kubectl config use-context'

# Programs
alias tmux='tmux -f ~/.config/tmux/tmux.conf'
alias less='less -XRF'

# dir movement
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

## Options Section
setopt appendhistory
setopt extendedglob
setopt histignorealldups
setopt histignorespace
setopt interactivecomments
setopt nocaseglob
setopt numericglobsort
setopt promptsubst
setopt rcexpandparam
setopt checkjobs

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' rehash true
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.config/zsh/cache
HISTFILE=~/.config/zsh/zsh_history
HISTSIZE=1000
SAVEHIST=500
WORDCHARS=${WORDCHARS//\/[&.;]}

## Keybinding Section
bindkey -v

# Home Key
bindkey '^[[7~' beginning-of-line
bindkey '^[[H' beginning-of-line

# End Key
bindkey '^[[8~' end-of-line
bindkey '^[[F' end-of-line

# Search
bindkey '^[[5~' history-beginning-search-backward # Page up key
bindkey '^[[6~' history-beginning-search-forward  # Page down key
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

## Theme Section
colors

## Plugin Section
source $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/plugins/zsh-git-prompt/zshrc.sh
source $ZDOTDIR/plugins/zsh-kubectl-prompt/kubectl.zsh
source <(kubectl completion zsh)
source <(minikube completion zsh)
source <(k9s completion zsh)
source <(kube-linter completion zsh)
source <(flux completion zsh)
source <(terraform-docs completion zsh)

# git prompt config
ZSH_THEME_GIT_PROMPT_PREFIX="["
ZSH_THEME_GIT_PROMPT_SUFFIX="]"
ZSH_THEME_GIT_PROMPT_HASH_PREFIX=":"
ZSH_THEME_GIT_PROMPT_SEPARATOR="|"
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[magenta]%}"
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[red]%}%{●%G%}"
ZSH_THEME_GIT_PROMPT_CONFLICTS="%{$fg[red]%}%{✖%G%}"
ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[blue]%}%{%G%}"
ZSH_THEME_GIT_PROMPT_BEHIND="%{↓%2G%}"
ZSH_THEME_GIT_PROMPT_BEHIND_AHEAD_SEPARATOR=""
ZSH_THEME_GIT_PROMPT_AHEAD="%{↑%2G%}"
ZSH_THEME_GIT_PROMPT_STASHED="%{$fg_bold[blue]%}%{%G%}"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[cyan]%}%{%G%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}%{✔%G%}"
ZSH_THEME_GIT_PROMPT_LOCAL=" L"
# The remote branch will be shown between these two
ZSH_THEME_GIT_PROMPT_UPSTREAM_FRONT=" {%{$fg_bold[blue]%}"
ZSH_THEME_GIT_PROMPT_UPSTREAM_END="%{${reset_color}%}}"

## Primary prompt
PS1='\
%F{reset_color}[ \
%B%F{14}%D%b \
%B%F{14}%T%b\
%F{reset_color} ] \
%B%F{11}%n%b\
%F{reset_color%}@\
%B%F{10}%m%b\
%B%F{12}%~%b\
%F{reset_color}
 %F{12}»\
%F{reset_color} \
'

## Local source
source ~/.config/zsh/.zshrc.local

## Tmux Section
if [[ -z "$TMUX" ]] ;then
    ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )"
    if [[ -z "$ID" ]] ;then
        tmux new-session
    else
        tmux attach-session -t "$ID"
    fi
fi

