#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#282936'

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod3

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-x close
hc keybind $Mod-Return spawn ${TERMINAL:-urxvt}
hc keybind $Mod-d spawn dmenu_run

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# resizing frames
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode


# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# move windows
hc keybind $Mod-Shift-period move_index +1 --skip-visible
hc keybind $Mod-Shift-comma  move_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
#hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# Settings
hc set frame_gap 0
hc set frame_padding 0
hc set window_gap -1
hc set frame_border_active_color '#00F769'
hc set frame_border_normal_color '#282936'
hc set frame_border_inner_color '#282936'
hc set frame_bg_active_color '#282936'
hc set frame_bg_normal_color '#282936'
hc set frame_bg_transparent 0
hc set frame_transparent_width 0
hc set frame_border_width 1
hc set frame_border_inner_width -1
hc set always_show_frame off
hc set frame_active_opacity 100
hc set frame_normal_opacity 100
hc set gapless_grid on
hc set smart_frame_surroundings on
hc set smart_window_surroundings on
hc set focus_follows_mouse off
hc set focus_stealing_prevention on
hc set tree_style '╾│ ├└╼─┐'

# Theme
hc attr theme.active.border_width 3
hc attr theme.normal.border_width 3
hc attr theme.urgent.border_width 3
hc attr theme.active.padding_top 0
hc attr theme.normal.padding_top 0
hc attr theme.urgent.padding_top 0
hc attr theme.active.padding_right 0
hc attr theme.normal.padding_right 0
hc attr theme.urgent.padding_right 0
hc attr theme.active.padding_bottom 0
hc attr theme.normal.padding_bottom 0
hc attr theme.urgent.padding_bottom 0
hc attr theme.active.padding_left 0
hc attr theme.normal.padding_left 0
hc attr theme.urgent.padding_left 0
hc attr theme.active.color '#00F769'
hc attr theme.normal.color '#282936'
hc attr theme.urgent.color '#EA51B2'
hc attr theme.active.inner_width 0
hc attr theme.normal.inner_width 1
hc attr theme.urgent.inner_width 0
hc attr theme.active.inner_color '#000000'
hc attr theme.normal.inner_color '#000000'
hc attr theme.urgent.inner_color '#000000'
hc attr theme.active.outer_width 0
hc attr theme.normal.outer_width 0
hc attr theme.urgent.outer_width 0
hc attr theme.active.outer_color '#000000'
hc attr theme.normal.outer_color '#000000'
hc attr theme.urgent.outer_color '#000000'
hc attr theme.active.background_color '#282936'
hc attr theme.normal.background_color '#282936'
hc attr theme.urgent.background_color '#282936'

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
